# Markov Chain Problem - Squirrel

Consider a squirrel trapped in a box divided into
9 rooms. This squirrel enjoys an active life style, so every minute, it decides to go through any of
the available doors or stay in the current room, where all actions are taken with equal probability.
See figure. For example, if the squirrel is in box 1 at time $t$, then at time $t$ + 1, it is in box 1, 2, or 4 with probability 1/3 each. For every minute $t$ = 0, 1, 2, . . . , let $x(t) ∈ R^9$ denote the vector whose $i$-th entry is the probability that the squirrel is in box $i$ at time $t$.

<img src="./S.png" width="100">

In [3]:
import numpy as np

### (a) Find a matrix P such that $x(t + 1) = P x(t)$.

In [4]:
col1 = np.array([1/3,1/3,0,1/3,0,0,0,0,0])
print(np.round(col1,2))

[0.33 0.33 0.   0.33 0.   0.   0.   0.   0.  ]


In [5]:
col2 = np.array([1/4,1/4,1/4,0,1/4,0,0,0,0])
col3 = np.array([0,1/3,1/3,0,0,1/3,0,0,0])
col4 = np.array([1/4,0,0,1/4,1/4,0,1/4,0,0])
col5 = np.array([0,1/5,0,1/5,1/5,1/5,0,1/5,0])
col6 = np.array([0,0,1/4,0,1/4,1/4,0,0,1/4])
col7 = np.array([0,0,0,1/3,0,0,1/3,1/3,0])
col8 = np.array([0,0,0,0,1/4,0,1/4,1/4,1/4])
col9 = np.array([0,0,0,0,0,1/3,0,1/3,1/3])

In [6]:
stacked = np.stack((col1,col2,col3,col4,col5,col6,col7,col8,col9), axis=-1)
P = np.matrix(stacked)
P.shape

(9, 9)

In [7]:
print(np.round(P,2))

[[0.33 0.25 0.   0.25 0.   0.   0.   0.   0.  ]
 [0.33 0.25 0.33 0.   0.2  0.   0.   0.   0.  ]
 [0.   0.25 0.33 0.   0.   0.25 0.   0.   0.  ]
 [0.33 0.   0.   0.25 0.2  0.   0.33 0.   0.  ]
 [0.   0.25 0.   0.25 0.2  0.25 0.   0.25 0.  ]
 [0.   0.   0.33 0.   0.2  0.25 0.   0.   0.33]
 [0.   0.   0.   0.25 0.   0.   0.33 0.25 0.  ]
 [0.   0.   0.   0.   0.2  0.   0.33 0.25 0.33]
 [0.   0.   0.   0.   0.   0.25 0.   0.25 0.33]]


P is the above matrix

### (b) Can you find an integer $k ≥ 1$ such that all entries of $P^k$ are strictly positive?

In [8]:
# k = 1
print(np.round(P, 2))

[[0.33 0.25 0.   0.25 0.   0.   0.   0.   0.  ]
 [0.33 0.25 0.33 0.   0.2  0.   0.   0.   0.  ]
 [0.   0.25 0.33 0.   0.   0.25 0.   0.   0.  ]
 [0.33 0.   0.   0.25 0.2  0.   0.33 0.   0.  ]
 [0.   0.25 0.   0.25 0.2  0.25 0.   0.25 0.  ]
 [0.   0.   0.33 0.   0.2  0.25 0.   0.   0.33]
 [0.   0.   0.   0.25 0.   0.   0.33 0.25 0.  ]
 [0.   0.   0.   0.   0.2  0.   0.33 0.25 0.33]
 [0.   0.   0.   0.   0.   0.25 0.   0.25 0.33]]


In [10]:
# k = 2
print(np.round(np.linalg.matrix_power(P, 2), 2))

[[0.28 0.15 0.08 0.15 0.1  0.   0.08 0.   0.  ]
 [0.19 0.28 0.19 0.13 0.09 0.13 0.   0.05 0.  ]
 [0.08 0.15 0.28 0.   0.1  0.15 0.   0.   0.08]
 [0.19 0.13 0.   0.28 0.09 0.05 0.19 0.13 0.  ]
 [0.17 0.11 0.17 0.11 0.24 0.11 0.17 0.11 0.17]
 [0.   0.13 0.19 0.05 0.09 0.28 0.   0.13 0.19]
 [0.08 0.   0.   0.15 0.1  0.   0.28 0.15 0.08]
 [0.   0.05 0.   0.13 0.09 0.13 0.19 0.28 0.19]
 [0.   0.   0.08 0.   0.1  0.15 0.08 0.15 0.28]]


In [12]:
# k = 3
print(np.round(np.linalg.matrix_power(P, 3), 2))

[[0.19 0.15 0.08 0.15 0.08 0.05 0.08 0.05 0.  ]
 [0.2  0.19 0.2  0.1  0.14 0.1  0.06 0.04 0.06]
 [0.08 0.15 0.19 0.05 0.08 0.15 0.   0.05 0.08]
 [0.2  0.1  0.06 0.19 0.14 0.04 0.2  0.1  0.06]
 [0.13 0.17 0.13 0.17 0.14 0.17 0.13 0.17 0.13]
 [0.06 0.1  0.2  0.04 0.14 0.19 0.06 0.1  0.2 ]
 [0.08 0.05 0.   0.15 0.08 0.05 0.19 0.15 0.08]
 [0.06 0.04 0.06 0.1  0.14 0.1  0.2  0.19 0.2 ]
 [0.   0.05 0.08 0.05 0.08 0.15 0.08 0.15 0.19]]


In [14]:
# k = 4
print(np.round(np.linalg.matrix_power(P, 4), 2))

[[0.16 0.12 0.09 0.12 0.09 0.05 0.09 0.05 0.03]
 [0.17 0.18 0.17 0.13 0.11 0.13 0.07 0.07 0.07]
 [0.09 0.12 0.16 0.05 0.09 0.12 0.03 0.05 0.09]
 [0.17 0.13 0.07 0.18 0.11 0.07 0.17 0.13 0.07]
 [0.16 0.14 0.16 0.14 0.16 0.14 0.16 0.14 0.16]
 [0.07 0.13 0.17 0.07 0.11 0.18 0.07 0.13 0.17]
 [0.09 0.05 0.03 0.12 0.09 0.05 0.16 0.12 0.09]
 [0.07 0.07 0.07 0.13 0.11 0.13 0.17 0.18 0.17]
 [0.03 0.05 0.09 0.05 0.09 0.12 0.09 0.12 0.16]]


In [16]:
print(np.linalg.matrix_power(P, 4)>0)

[[ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]]


when k = 4, $P^k$ are strictly positive

### (c) Suppose that at time 0, the squirrel is in room 1. In 10 minutes, what is the probability the squirrel will be in each of the 9 rooms? (That is, if $x(0) = e_1 ∈ R^9$, then compute $x(10)$.

In [17]:
# t = 0
stage_0 = np.matrix(np.array([1,0,0,0,0,0,0,0,0])).transpose()
stage_0.shape

(9, 1)

In [18]:
# t = 1
stage_1 = P@stage_0
print(np.round(stage_1,2))

[[0.33]
 [0.33]
 [0.  ]
 [0.33]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]]


In [19]:
# t = 2
stage_2 = np.linalg.matrix_power(P, 2)@stage_0
print(np.round(stage_2, 3))

[[0.278]
 [0.194]
 [0.083]
 [0.194]
 [0.167]
 [0.   ]
 [0.083]
 [0.   ]
 [0.   ]]


In [20]:
# t = 10
stage_10 = np.linalg.matrix_power(P, 10)@stage_0
print(np.round(stage_10, 3))

[[0.099]
 [0.127]
 [0.091]
 [0.127]
 [0.152]
 [0.115]
 [0.091]
 [0.115]
 [0.083]]


The above vector contains the caculated probablity that the squirrel will be in each of the 9 rooms in 10 minutes, respectively.

In [21]:
l_stage_10 = stage_10.tolist()
for i, v in enumerate(l_stage_10):
    print(f'The probability that the squirrel will be in room {i} in 10 minutes is {round(v[0], 3)}.')

The probability that the squirrel will be in room 0 in 10 minutes is 0.099.
The probability that the squirrel will be in room 1 in 10 minutes is 0.127.
The probability that the squirrel will be in room 2 in 10 minutes is 0.091.
The probability that the squirrel will be in room 3 in 10 minutes is 0.127.
The probability that the squirrel will be in room 4 in 10 minutes is 0.152.
The probability that the squirrel will be in room 5 in 10 minutes is 0.115.
The probability that the squirrel will be in room 6 in 10 minutes is 0.091.
The probability that the squirrel will be in room 7 in 10 minutes is 0.115.
The probability that the squirrel will be in room 8 in 10 minutes is 0.083.


### d)  Compute the invariant measure for this problem.

In [22]:
w, v = np.linalg.eig(P)
print(np.round(w, 3),"\n")
print(np.round(v, 3))

[-0.467  1.     0.333  0.25   0.702 -0.119 -0.119  0.702  0.25 ] 

[[ 0.224 -0.268  0.5    0.256  0.489  0.436  0.252  0.064  0.075]
 [-0.358 -0.358  0.    -0.043  0.361 -0.394 -0.549 -0.311 -0.49 ]
 [ 0.224 -0.268 -0.5    0.256  0.    -0.     0.355 -0.485  0.075]
 [-0.358 -0.358 -0.    -0.043  0.361 -0.394  0.094  0.405  0.465]
 [ 0.537 -0.447 -0.    -0.854 -0.    -0.    -0.    -0.    -0.251]
 [-0.358 -0.358 -0.    -0.043 -0.361  0.394 -0.094 -0.405  0.465]
 [ 0.224 -0.268 -0.5    0.256  0.     0.    -0.355  0.485  0.075]
 [-0.358 -0.358  0.    -0.043 -0.361  0.394  0.549  0.311 -0.49 ]
 [ 0.224 -0.268  0.5    0.256 -0.489 -0.436 -0.252 -0.064  0.075]]


In [23]:
D = np.diag(w)
print(np.round(D, 3))

[[-0.467  0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     1.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.333  0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.25   0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.702  0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.    -0.119  0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.    -0.119  0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.702  0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.25 ]]


In [24]:
D_inf = D.copy()
# When the power of P gets infinately large, 
# the factions in the matrix becomes infinately cloase to 0 and drop off
D_inf[D<1] = 0
print(D_inf)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [25]:
U = v
U_inv = np.linalg.inv(U)
print(np.round(U@U_inv, 2))

[[ 1. -0. -0.  0. -0. -0. -0. -0. -0.]
 [ 0.  1. -0.  0. -0.  0. -0.  0.  0.]
 [ 0.  0.  1. -0. -0. -0.  0.  0.  0.]
 [ 0.  0. -0.  1. -0.  0.  0. -0. -0.]
 [ 0. -0.  0. -0.  1.  0.  0.  0. -0.]
 [ 0. -0. -0. -0. -0.  1. -0.  0.  0.]
 [-0. -0. -0. -0.  0.  0.  1. -0. -0.]
 [-0. -0. -0.  0.  0.  0.  0.  1.  0.]
 [-0. -0.  0.  0. -0. -0. -0.  0.  1.]]


In [26]:
stage_n = U@D_inf@U_inv@stage_0
print(np.round(stage_n, 3))

[[0.091]
 [0.121]
 [0.091]
 [0.121]
 [0.152]
 [0.121]
 [0.091]
 [0.121]
 [0.091]]


In [27]:
# Verify that u = Pu
print(np.round(P@stage_n, 3))

[[0.091]
 [0.121]
 [0.091]
 [0.121]
 [0.152]
 [0.121]
 [0.091]
 [0.121]
 [0.091]]


The above vector is the invariant measure for Matrix P in this problem.

### e) You plan to check the box in 10 years to see your old friend, this squirrel. Which room should you arrive in so as to maximize the probability that when you arrive, the squirrel is in the same room?

In [22]:
print(np.argmax(stage_n) + 1)

5


Room 5 is the room I should arrive in because it yields the highest probablity in the invariant measure and is the room with the highest probablity that the squirrel will be in.